version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lead-db
    environment:
      POSTGRES_USER: byteforge
      POSTGRES_PASSWORD: 2456B-MA96j
      POSTGRES_DB: byteforge_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  java-app:
    image: lead-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/byteforge_db
      SPRING_DATASOURCE_USERNAME: byteforge
      SPRING_DATASOURCE_PASSWORD: 2456B-MA96j
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: