spring:
  application:
    name: project001

  datasource:
    url: jdbc:postgresql://postgres:5432/byteforge_db
    username: byteforge
    password: 2456B-MA96j

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    queue: user-verification-queue
    exchange: user-verification-exchange
    routing-key: user.verification

  mail:
    host: mailhog
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false